### ISSUE TITLE
// mirror_master branches don't deploy why?

### ISSUE THREAD

**Issue by nomean42** [Strider-CD/strider-bitbucket#34]
api.js str 284 
why so, @jaredly ?

**Comment by oliversalzburg** [comment]
Translation: Why are `mirror_master` branches set to not deploy? For reference: https://github.com/Strider-CD/strider-bitbucket/blob/master/lib/api.js#L284

**Comment by knownasilya** [comment]
Should we clarify in the UI, or is the behavior weird?

**Comment by nomean42** [comment]
It is weird, im working with framework and there is only one way to deploy my app, so all my branches are mirrored with master.

**Comment by oliversalzburg** [comment]
This might have something to do with it:

![image](https://cloud.githubusercontent.com/assets/1658949/15350067/7762c908-1cd7-11e6-8031-caf164ac7c8c.png)

If you want to deploy those branches, customize them and check the **Deploy on green* option.

I'm not sure why this exception is made specifically in the plugin. I assumed this was handled globally. But, to my understanding, it's by design.

**Comment by nomean42** [comment]
@oliversalzburg how often do you deploy non master branch?

**Comment by oliversalzburg** [comment]
@nomean42 Somewhere between *never* and *constantly*, depending on the project.

**Comment by nomean42** [comment]
okay
